version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: 'ci(dependabot):'
  labels:
  - ci
  - dependencies
- package-ecosystem: python
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: 'ci(dependabot):'
  labels:
  - ci
  - dependencies
  allow:
  - dependency-name: "sionna"
